# Generated by Django 4.2.7 on 2026-03-25 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('detection', 'Waste Detection'), ('alert', 'Contamination Alert'), ('manual', 'Manual Sort')], default='detection', max_length=20)),
                ('detected_class', models.CharField(choices=[('plastic', 'Plastic'), ('metal', 'Metal'), ('paper', 'Paper'), ('glass', 'Glass'), ('cardboard', 'Cardboard'), ('organic', 'Organic'), ('trash', 'Trash')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('alert_triggered', models.BooleanField(default=False)),
                ('alert_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('image_base64', models.TextField(blank=True, null=True)),
                ('worker_corrected', models.BooleanField(default=False)),
                ('worker_corrected_class', models.CharField(blank=True, choices=[('plastic', 'Plastic'), ('metal', 'Metal'), ('paper', 'Paper'), ('glass', 'Glass'), ('cardboard', 'Cardboard'), ('organic', 'Organic'), ('trash', 'Trash')], max_length=20, null=True)),
                ('worker_notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=50)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('test_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_performance', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='SortingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shift', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=20, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_detections', models.IntegerField(default=0)),
                ('total_alerts', models.IntegerField(default=0)),
                ('worker_interventions', models.IntegerField(default=0)),
                ('average_confidence', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ContaminationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_class', models.CharField(choices=[('plastic', 'Plastic'), ('metal', 'Metal'), ('paper', 'Paper'), ('glass', 'Glass'), ('cardboard', 'Cardboard'), ('organic', 'Organic'), ('trash', 'Trash')], max_length=20)),
                ('target_class', models.CharField(choices=[('plastic', 'Plastic'), ('metal', 'Metal'), ('paper', 'Paper'), ('glass', 'Glass'), ('cardboard', 'Cardboard'), ('organic', 'Organic'), ('trash', 'Trash')], max_length=20)),
                ('alert_enabled', models.BooleanField(default=True)),
                ('alert_message', models.CharField(default='Contamination detected!', max_length=200)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
            ],
            options={
                'unique_together': {('detected_class', 'target_class')},
            },
        ),
    ]
